In [2]:
import torch

In [3]:
x=torch.empty(2,1,2,3)
x

tensor([[[[0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.]]]])

In [4]:
x=torch.rand(2,3)
x

tensor([[0.9231, 0.1104, 0.2753],
        [0.3135, 0.1950, 0.8566]])

In [5]:
x=torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
x=torch.ones(1,5)
x

tensor([[1., 1., 1., 1., 1.]])

In [7]:
print(x.dtype) # float bydefault

torch.float32


In [8]:
x=torch.ones(1,5, dtype=torch.int)
print(x.dtype)
print(x)


torch.int32
tensor([[1, 1, 1, 1, 1]], dtype=torch.int32)


In [9]:
x.size() #size function

torch.Size([1, 5])

In [10]:
x=torch.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])

In [11]:
x=torch.rand(2,2)
y=torch.rand(2,2)
z=x+y #way1
print(x)
print(y)
print(z)
z2=torch.add(x,y) #way2
print(z2)
y.add_(x) #inplace addition(way3)
print(y)

tensor([[0.3897, 0.3478],
        [0.8326, 0.3836]])
tensor([[0.9345, 0.5642],
        [0.5520, 0.1617]])
tensor([[1.3242, 0.9120],
        [1.3847, 0.5452]])
tensor([[1.3242, 0.9120],
        [1.3847, 0.5452]])
tensor([[1.3242, 0.9120],
        [1.3847, 0.5452]])


In [12]:
x=torch.rand(2,2)
y=torch.rand(2,2)
z=x-y #way1
print(x)
print(y)
print(z)
z2=torch.sub(x,y) #way2
print(z2)
y.sub_(x) #inplace sub(way3)
print(y)

tensor([[0.6806, 0.1795],
        [0.6962, 0.2163]])
tensor([[0.1167, 0.2540],
        [0.7000, 0.5610]])
tensor([[ 0.5638, -0.0745],
        [-0.0038, -0.3448]])
tensor([[ 0.5638, -0.0745],
        [-0.0038, -0.3448]])
tensor([[-0.5638,  0.0745],
        [ 0.0038,  0.3448]])


In [13]:
x=torch.rand(2,2)
y=torch.rand(2,2)
z=x*y #way1
print(x)
print(y)
print(z)
z2=torch.mul(x,y) #way2
print(z2)
y.mul_(x) #inplace mul(way3)
print(y)

tensor([[0.0314, 0.9852],
        [0.5910, 0.1910]])
tensor([[0.9168, 0.6766],
        [0.5357, 0.4041]])
tensor([[0.0288, 0.6666],
        [0.3166, 0.0772]])
tensor([[0.0288, 0.6666],
        [0.3166, 0.0772]])
tensor([[0.0288, 0.6666],
        [0.3166, 0.0772]])


In [14]:
x=torch.rand(2,2)
y=torch.rand(2,2)
z=x/y #way1
print(x)
print(y)
print(z)
z2=torch.div(x,y) #way2
print(z2)
x.div_(y) #inplace div(way3)
print(x)

tensor([[0.3768, 0.0301],
        [0.9697, 0.7750]])
tensor([[0.1176, 0.1402],
        [0.0044, 0.9851]])
tensor([[3.2032e+00, 2.1450e-01],
        [2.1973e+02, 7.8672e-01]])
tensor([[3.2032e+00, 2.1450e-01],
        [2.1973e+02, 7.8672e-01]])
tensor([[3.2032e+00, 2.1450e-01],
        [2.1973e+02, 7.8672e-01]])


In [15]:
x=torch.rand(5,3)
print(x)
print(x[:,0]) #all rows of 0th column
print(x[1,1]) #1st row 1st column
print(x[1,1].item()) #1st row 1st column value(item-single value output)


tensor([[0.8723, 0.2837, 0.5677],
        [0.5317, 0.8001, 0.5562],
        [0.4868, 0.7704, 0.1911],
        [0.8673, 0.8440, 0.7412],
        [0.6308, 0.4134, 0.3169]])
tensor([0.8723, 0.5317, 0.4868, 0.8673, 0.6308])
tensor(0.8001)
0.8001161217689514


In [16]:
x=torch.rand(4,4)
print(x)
y=x.view(16) #reshaping
print(y)
print(y.size())
print(y.shape)
y=x.view(-1,8) #reshaping.. -1 means automatically calculate
print(y)
print(y.size())
print(y.shape)

tensor([[0.1757, 0.6713, 0.0601, 0.7643],
        [0.0206, 0.3901, 0.7960, 0.6083],
        [0.1174, 0.4860, 0.4456, 0.5613],
        [0.0028, 0.1528, 0.1427, 0.3767]])
tensor([0.1757, 0.6713, 0.0601, 0.7643, 0.0206, 0.3901, 0.7960, 0.6083, 0.1174,
        0.4860, 0.4456, 0.5613, 0.0028, 0.1528, 0.1427, 0.3767])
torch.Size([16])
torch.Size([16])
tensor([[0.1757, 0.6713, 0.0601, 0.7643, 0.0206, 0.3901, 0.7960, 0.6083],
        [0.1174, 0.4860, 0.4456, 0.5613, 0.0028, 0.1528, 0.1427, 0.3767]])
torch.Size([2, 8])
torch.Size([2, 8])


In [17]:
import numpy as np

In [18]:
a=torch.ones(5)
print(a)
print(type(a))
b=a.numpy()
print(b)
print(type(b))
#tensor is in CPU and not GPU, then both objects share same memory location
#changing numpy array will change tensor
#changing tensor will change numpy array
a.add_(4)
print(b)
print(a)

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
[5. 5. 5. 5. 5.]
tensor([5., 5., 5., 5., 5.])


In [19]:
a=np.ones(5)
print(a)
print(type(a))
b=torch.from_numpy(a)
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [20]:
torch.cuda.is_available()

False

In [21]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    x=torch.ones(5,device=device)
    y=torch.ones(5)
    y=y.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))
    z=z.to("cpu",torch.double)

In [22]:
x=torch.ones(5,requires_grad=True) 
#Tells pytorch to calculate gradients for this tensor later during optimization steps.
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
