In [1]:
import torch

In [2]:
x=torch.randn(3,requires_grad=True)
print(x)

tensor([ 0.3443, -1.3422, -0.4349], requires_grad=True)


In [3]:
y=x+2
print(y)

tensor([2.3443, 0.6578, 1.5651], grad_fn=<AddBackward0>)


In [5]:
z=y*y*2
print(z)
z=z.mean()
print(z)

tensor(5.5854, grad_fn=<MeanBackward0>)


In [6]:
z.backward() #dz/dx
print(x.grad)

tensor([3.1257, 0.8771, 2.0868])


In [10]:
z=y*y*2
print(z)
v=torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
z.backward(v) #jacobian vector product
#vector v is needed if z is not scalar
print(x.grad)

tensor([10.9915,  0.8655,  4.8992], grad_fn=<MulBackward0>)
tensor([5.0012, 6.1398, 2.0994])


In [13]:
x=torch.randn(3,requires_grad=True)
print(x)
#way 1 for disabling gradient tracking
x.requires_grad_(False) #inplace
print(x)
#way 2 for disabling gradient tracking
y=x.detach() #new tensor that does not require grad
print(y)
#way 3
with torch.no_grad():
    y=x+2
    print(y)

tensor([ 0.5850, -0.4304, -0.6160], requires_grad=True)
tensor([ 0.5850, -0.4304, -0.6160])
tensor([ 0.5850, -0.4304, -0.6160])
tensor([2.5850, 1.5696, 1.3840])


In [14]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(1):
    model_op=(weights*3).sum()
    model_op.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])


In [16]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(3):
    model_op=(weights*3).sum()
    model_op.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [17]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(3):
    model_op=(weights*3).sum()
    model_op.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
